@extends('layouts.default')
@section('content')



<button type="button" onclick="displayCookies()">Display All Cookies</button>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquam molestie erat, et semper massa auctor in. Etiam dignissim, dui sit amet pellentesque bibendum, magna nisl pretium diam, sodales semper ligula tortor eget quam. Pellentesque nec odio tellus. Donec metus libero, malesuada eu libero eu, accumsan vulputate elit. Cras maximus fermentum velit, a finibus massa sagittis in. Morbi in enim lectus. Pellentesque feugiat ut felis eu faucibus.
    <br><br><img src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-grey-260nw-1072447043.jpg" class="img-fluid"><br>
<p>Phasellus enim magna, imperdiet at magna sed, bibendum euismod elit. Vivamus quis blandit sapien. Morbi vitae eleifend dolor, laoreet efficitur metus. Nulla malesuada risus dignissim, luctus leo eu, commodo mauris. Duis dapibus velit at tellus elementum volutpat. Duis tempor lacinia accumsan. Integer lorem enim, mattis nec dignissim sit amet, facilisis eget sem. Duis at erat dolor. Suspendisse vitae cursus mi. Donec a diam magna. In condimentum ultrices diam, ac vestibulum orci fringilla eget. Ut ligula quam, egestas nec consequat nec, dapibus vel nisi. Suspendisse vehicula massa ut velit posuere, vitae tempor tortor pulvinar. Nam ac posuere tortor, non convallis sem.</p>
<!--<br><img src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-grey-260nw-1072447043.jpg" class="img-fluid">-->
<p>Maecenas commodo hendrerit nisl, in gravida urna fringilla et. Pellentesque ligula sem, rhoncus quis ante id, consequat auctor leo. In hac habitasse platea dictumst. Pellentesque in nunc maximus, porta diam in, bibendum elit. Donec tincidunt convallis condimentum. Maecenas id condimentum ligula. Phasellus nec leo et elit ultrices ultrices. Nam nec nunc nec orci lacinia ornare. Integer luctus aliquam risus, id sollicitudin dolor auctor sit amet. Cras odio massa, tristique vel semper at, suscipit ut justo. Etiam elementum tortor luctus lacus dapibus, in lobortis orci porttitor. Duis congue mauris velit, a sodales elit porta in. Duis accumsan, dui vel iaculis fermentum, tortor mi laoreet enim, vel elementum dolor massa ut libero. Nulla pharetra metus a nunc aliquet, blandit lobortis enim auctor. Sed pellentesque non nisi ac mollis. In non purus vitae erat consequat accumsan eu eget lectus.</p>
<br><img src="https://alumni.crg.eu/sites/default/files/default_images/default-picture_0_0.png" class="img-fluid">
<p>Praesent at rhoncus dui. Nunc scelerisque efficitur augue vitae tincidunt. Curabitur bibendum, erat eget accumsan mollis, ex diam convallis est, non lobortis arcu elit quis leo. Nullam sit amet arcu auctor, ornare dui sed, porta sem. Donec quam turpis, pulvinar sed laoreet non, mattis non magna. Nullam leo augue, congue sollicitudin tempus sed, dignissim sed sem. In varius sem in erat scelerisque, et euismod orci condimentum. Etiam laoreet fringilla risus, ac maximus leo tristique vitae.</p>
<br><img src="https://alumni.crg.eu/sites/default/files/default_images/default-picture_0_0.png" class="img-fluid">
<p>Vivamus ullamcorper consectetur commodo. Suspendisse accumsan suscipit aliquam. Sed vitae massa a nisl dignissim mattis auctor sit amet sem. Pellentesque id sollicitudin dolor. Nunc ac tellus at velit gravida luctus. Vestibulum tristique dolor magna, efficitur elementum odio condimentum quis. Pellentesque eleifend a mi id semper. Suspendisse at fringilla felis, eu pharetra tortor. Nulla facilisi. Vivamus vehicula imperdiet purus, et accumsan eros lacinia non. Vivamus erat metus, mattis sed vulputate cursus, tristique a turpis. Mauris metus mi, cursus in urna vitae, egestas sagittis nulla. Nam malesuada urna placerat, lobortis lorem in, hendrerit augue. Maecenas metus ligula, scelerisque et ipsum ac, volutpat porttitor justo.</p>
<br><img src="https://alumni.crg.eu/sites/default/files/default_images/default-picture_0_0.png" class="img-fluid">

@stop